# 项目信息
site_name: opengl book
site_description: opengl book 是教程文档，beanflame哲学研究教程文档设计工程计划，尝试写得很细，语言要通俗易懂，希望能够建立起一个完善的教程。
site_author: beanflame
# site_url: https://opengl-book.beanflame.cn/


# 存储库
repo_name: 'beanflame/opengl-book'
repo_url: 'https://github.com/beanflame/opengl-book'
edit_uri: edit/main/docs/


# 版权
copyright: 'Copyright &copy; 2021 - 2021 opengl-book'


# 目录
nav:
  - 主页: 'index.md'
  - OpenGL Book:
    - 主页: 'opengl-book/index.md'
    - 简介: 'opengl-book/intro.md'
    - 入门:
      - OpenGL: 'opengl-book/1-introduction/1-OpenGL.md'
      - OpenGL配置: 'opengl-book/1-introduction/2-OpenGL-Configuration.md'
      - 创建窗口: 'opengl-book/1-introduction/3-Create-Window.md'
    - 主题: 'theme.md'

theme:
  name: null
  custom_dir: 'material'

  # Static files
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: zh
  features:
    - content.code.annotate
    - content.tabs.link
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    # - toc.integrate
    
  palette:
    scheme: default

#  palette:
#    - scheme: default
#      primary: indigo
#      accent: indigo
#      toggle:
#        icon: material/toggle-switch-off-outline
#        name: 切换到黑暗模式
#        
#    - scheme: slate
#      primary: red
#      accent: red
#      toggle:
#        icon: material/toggle-switch
#        name: 切换到灯光模式

  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo


# 定制
extra:
  search:
    language: 'zh'
  disqus: 'opengl-book'
  copyright: '<a href="https://creativecommons.org/licenses/by-sa/4.0/deed.zh">CC BY-SA 4.0</a> 和 <a href="https://github.com/zTrix/sata-license">SATA</a>'
  pagetime: 'on'
  manifest: 'manifest.webmanifest'
  githash: ''


extra_javascript:
  - '_static/js/extra.js?v=16'
  - 'https://cdn.jsdelivr.net/npm/mathjax@2.7.5/MathJax.js?config=TeX-MML-AM_CHTML'

extra_css:
  # - '_static/css/extra.css?v=13'
  - '_static/css/colortab.css'

# 扩展
markdown_extensions:
  # - colortab
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.progressbar
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
